### PR TITLE
fixes #114 created variable for breakpoint and fixed responsiveness

### LINKED ISSUE #114: Add 3 breakpoints
Breakpoints for 
1. Laptop
2.Tablet 
3.Mobile

### PR DESCRIPTION
**Pull request by shriaas2898**
* Created variable for max screen size for tab and mobile.
* Since mobile view is same as tab there is media query for only one break point.
* Fixed responsiveness of search form.
* Fixed position of hamburger menu in webview:
image
@rahulsavaria please check.

### CODE REVIEW

**Comment by AJV009** [comment]
Amazing!

**Comment by JayKandari** [comment]
@shriaas2898 : Please resolve conflicts.

**Comment by shriaas2898** [comment]
> @shriaas2898 : Please resolve conflicts.

Done!

**Review by JayKandari — APPROVED** [review]
LGTM.

**Pull request merged**
