### PR TITLE
 #32, #8: Fix config.php + Add dbConn.php + Fix sessionCookie.php

### PR DESCRIPTION
**Pull request by AJV009**
## Changes made
- Fixed errors and access levels in resources/src/config.php
- Added resources/src/dbConn.php which contains a hacky method to make quick queries as I mentioned in https://github.com/JayKandari/bookhive/issues/8#issuecomment-696330392 and https://github.com/JayKandari/bookhive/issues/29#issuecomment-696710491
- Fixed queries in resources/src/sessionCookie.php

## Critical PR

### CODE REVIEW

**Comment by AJV009** [comment]
@guptahemant @JayKandari pls review! 😁️

**Comment by AJV009** [comment]
@shriaas2898 @anjali-rathod @pragzii3896 I have updated the table structure a bit, replaced 'rid' in user with 'type' which will contain a default value 'user' and can only be changed or updated by a admin. Good? Can we go ahead with 'type'?

**Comment by shriaas2898** [comment]
@AJV009 don't include `$_SERVER["DOCUMENT_ROOT"]` in the path, it will give path starting from `/` which is fine for file system  but the server doesn't recognize it. Just put a `/` instead of `$_SERVER["DOCUMENT_ROOT"]`

**Comment by AJV009** [comment]
> @AJV009 don't include `$_SERVER["DOCUMENT_ROOT"]` in the path, it will give path starting from `/` which is fine for file system but the server doesn't recognize it. Just put a `/` instead of `$_SERVER["DOCUMENT_ROOT"]`

@shriaas2898  Am facing the opposite error, `/` or `../` is not working for me, `$_SERVER["DOCUMENT_ROOT"]` worked for me so am confused

**Comment by shriaas2898** [comment]
> > @AJV009 don't include `$_SERVER["DOCUMENT_ROOT"]` in the path, it will give path starting from `/` which is fine for file system but the server doesn't recognize it. Just put a `/` instead of `$_SERVER["DOCUMENT_ROOT"]`
> 
> Am facing the opposite error, `/` or `../` is not working for me, `$_SERVER["DOCUMENT_ROOT"]` worked for me so am confused 

`$_SERVER["DOCUMENT_ROOT"]` is not working for me :O

**Comment by AJV009** [comment]
> > > @AJV009 don't include `$_SERVER["DOCUMENT_ROOT"]` in the path, it will give path starting from `/` which is fine for file system but the server doesn't recognize it. Just put a `/` instead of `$_SERVER["DOCUMENT_ROOT"]`
> > 
> > 
> > Am facing the opposite error, `/` or `../` is not working for me, `$_SERVER["DOCUMENT_ROOT"]` worked for me so am confused
> 
> `$_SERVER["DOCUMENT_ROOT"]` is not working for me :O

mmm what should I do then?
mm let me see if I can find a fix

**Comment by AJV009** [comment]
> > > @AJV009 don't include `$_SERVER["DOCUMENT_ROOT"]` in the path, it will give path starting from `/` which is fine for file system but the server doesn't recognize it. Just put a `/` instead of `$_SERVER["DOCUMENT_ROOT"]`
> > 
> > 
> > Am facing the opposite error, `/` or `../` is not working for me, `$_SERVER["DOCUMENT_ROOT"]` worked for me so am confused
> 
> `$_SERVER["DOCUMENT_ROOT"]` is not working for me :O

Can you print your ` $_SERVER["DOCUMENT_ROOT"] `?

**Comment by shriaas2898** [comment]
> > > > @AJV009 don't include `$_SERVER["DOCUMENT_ROOT"]` in the path, it will give path starting from `/` which is fine for file system but the server doesn't recognize it. Just put a `/` instead of `$_SERVER["DOCUMENT_ROOT"]`
> > > 
> > > 
> > > Am facing the opposite error, `/` or `../` is not working for me, `$_SERVER["DOCUMENT_ROOT"]` worked for me so am confused
> > 
> > 
> > `$_SERVER["DOCUMENT_ROOT"]` is not working for me :O
> 
> Can you print your `$_SERVER["DOCUMENT_ROOT"]`?

`/var/www/book-hive/Book-Hive`

**Comment by AJV009** [comment]
> > > > > @AJV009 don't include `$_SERVER["DOCUMENT_ROOT"]` in the path, it will give path starting from `/` which is fine for file system but the server doesn't recognize it. Just put a `/` instead of `$_SERVER["DOCUMENT_ROOT"]`
> > > > 
> > > > 
> > > > Am facing the opposite error, `/` or `../` is not working for me, `$_SERVER["DOCUMENT_ROOT"]` worked for me so am confused
> > > 
> > > 
> > > `$_SERVER["DOCUMENT_ROOT"]` is not working for me :O
> > 
> > 
> > Can you print your `$_SERVER["DOCUMENT_ROOT"]`?
> 
> `/var/www/book-hive/Book-Hive`

mmm why do you have ` book-hive/Book-Hive `

**Comment by AJV009** [comment]
@shriaas2898 this is my configuration ->
 vhost set for ` bookhive.io ` (offcourse you guys can have different local vhost names, that doesn't matter)
Well my root of the document is ` bookhive.io `
So my ` $_SERVER["DOCUMENT_ROOT"] ` is ` /var/www/bookhive.io/ `

Maybe I'll add about vhost to the readme, should I?

**Comment by guptahemant** [comment]
You all can use `$_SERVER["DOCUMENT_ROOT"]`, It should be fine, / points to relative path in the current folder which sometimes cannot work depending on the location from which it is called, whereas if you use absolute path it will surely give you the correct path everytime.

**Comment by AJV009** [comment]
@guptahemant so can I get this merged now?

**Comment by guptahemant** [comment]
Merging it now, So that everyone can verify if it works for them, If it doesn't work, please raise a follow up for the fixes.

**Review by guptahemant — APPROVED** [review]

**Pull request merged**
