### PR TITLE
47 sidebar menus

### PR DESCRIPTION
**Pull request by shriaas2898**
#47: Added menu items in sidebar
Fixed Menu links for logged in user, previously `index.php`,`contact us` etc  used to load anonymous user's menu items, fixed it to load respective user's menu item.

### CODE REVIEW

**Comment by shriaas2898** [comment]
@JayKandari squashed the changes can you please check?

**Comment by AJV009** [comment]
@shriaas2898 YOUR SESSION CODE REPLACED MY METHODS IMPLEMENTATION IN https://github.com/JayKandari/bookhive/pull/61
NOW I HAVE TO FIND AND DO IT AGAIN!

**Comment by shriaas2898** [comment]
Oh damn sorry! @AJV009, @JayKandari can you revert this commit?

**Comment by AJV009** [comment]
> Oh damn sorry! @AJV009, @JayKandari can you revert this commit?

no no there are some changes in my PR

**Comment by AJV009** [comment]
DONT REVERT FOR GODS SAKE
I just found some useful code!
@shriaas2898  @JayKandari

**Pull request merged**
